/**
 * experiences.js
 *
 * Central configuration for all three experiences and their sub-themes.
 * Each sub-theme defines visual tokens that ThemeContext uses to apply
 * CSS classes and pass config to components. Educational data is untouched.
 *
 * Token reference:
 *   palette       — CSS variable overrides
 *   atmosphere    — 'light' | 'dark' | 'ultra-dark'
 *   cardShape     — 'sharp' | 'rounded' | 'rounded-xl' | 'pill'
 *   cardBorder    — 'none' | 'subtle' | 'accent' | 'glow'
 *   fontDisplay   — Display font name (loaded via Google Fonts in index.html or dynamic)
 *   progressStyle — 'bar' | 'orbs' | 'xp-ring' | 'film-strip' | 'stardust'
 *   artwork       — Key for ThemeArtwork component
 *   buttonStyle   — 'square' | 'rounded' | 'pill'
 *   micro         — Micro-interaction class key ('bounce'|'glow'|'sparkle'|'flicker'|'slide')
 */

// ─────────────────────────────────────────────
// PROFESSIONAL
// ─────────────────────────────────────────────
const professional = {
    label: 'Professional',
    emoji: '💼',
    description: 'Focused, clean, and results-driven.',
    reward: { key: 'points', label: 'Points', unit: 'pts', emoji: '⭐' },
    terminology: {
        chapter: 'Chapter',
        topic: 'Topic',
        assessment: 'Assessment',
        progress: 'Progress',
        streak: 'Study Streak',
        complete: 'Completed',
        locked: 'Locked',
        level: 'Level',
    },
    defaultSubTheme: 'corporate',
    subThemes: {
        corporate: {
            label: 'Corporate',
            emoji: '🏢',
            description: 'Boardroom-ready. Confident lines and sharp clarity.',
            palette: {
                '--primary': '#1e40af',
                '--secondary': '#3b82f6',
                '--accent': '#0ea5e9',
                '--background': '#f8fafc',
                '--surface': 'rgba(255,255,255,0.97)',
                '--glass': 'rgba(255,255,255,0.75)',
                '--text': '#0f172a',
                '--text-muted': '#475569',
                '--card-border': 'rgba(0,0,0,0.07)',
                '--input-bg': '#ffffff',
                '--input-border': 'rgba(0,0,0,0.12)',
                '--theme-accent-glow': 'rgba(30,64,175,0.15)',
                '--theme-sidebar-bg': '#f1f5f9',
                '--theme-progress-color': '#1e40af',
            },
            atmosphere: 'light',
            cardShape: 'rounded',
            cardBorder: 'subtle',
            fontDisplay: 'Inter',
            progressStyle: 'bar',
            artwork: 'geo-lines',
            buttonStyle: 'rounded',
            micro: 'slide',
        },
        academic: {
            label: 'Academic',
            emoji: '🎓',
            description: 'University-library calm. Serif warmth and scholarly detail.',
            palette: {
                '--primary': '#7c3aed',
                '--secondary': '#a78bfa',
                '--accent': '#ddd6fe',
                '--background': '#faf7ff',
                '--surface': 'rgba(255,255,255,0.95)',
                '--glass': 'rgba(245,243,255,0.8)',
                '--text': '#1e1b4b',
                '--text-muted': '#6d6a8a',
                '--card-border': 'rgba(124,58,237,0.08)',
                '--input-bg': '#ffffff',
                '--input-border': 'rgba(124,58,237,0.15)',
                '--theme-accent-glow': 'rgba(124,58,237,0.12)',
                '--theme-sidebar-bg': '#f5f3ff',
                '--theme-progress-color': '#7c3aed',
            },
            atmosphere: 'light',
            cardShape: 'rounded-xl',
            cardBorder: 'accent',
            fontDisplay: 'Lora',
            progressStyle: 'bar',
            artwork: 'bookshelf',
            buttonStyle: 'rounded',
            micro: 'slide',
        },
        minimal: {
            label: 'Minimal',
            emoji: '⬜',
            description: 'Pure white space. Nothing between you and your focus.',
            palette: {
                '--primary': '#18181b',
                '--secondary': '#52525b',
                '--accent': '#a1a1aa',
                '--background': '#ffffff',
                '--surface': 'rgba(255,255,255,1)',
                '--glass': 'rgba(255,255,255,0.9)',
                '--text': '#09090b',
                '--text-muted': '#71717a',
                '--card-border': 'rgba(0,0,0,0.06)',
                '--input-bg': '#fafafa',
                '--input-border': 'rgba(0,0,0,0.08)',
                '--theme-accent-glow': 'rgba(0,0,0,0.05)',
                '--theme-sidebar-bg': '#f4f4f5',
                '--theme-progress-color': '#18181b',
            },
            atmosphere: 'light',
            cardShape: 'sharp',
            cardBorder: 'none',
            fontDisplay: 'Inter',
            progressStyle: 'bar',
            artwork: 'minimal-dots',
            buttonStyle: 'square',
            micro: 'slide',
        },
        'dark-pro': {
            label: 'Dark',
            emoji: '🌑',
            description: 'Late-night focus mode. Navy depth with electric blue accents.',
            palette: {
                '--primary': '#60a5fa',
                '--secondary': '#93c5fd',
                '--accent': '#3b82f6',
                '--background': '#0a0f1e',
                '--surface': 'rgba(15,23,42,0.95)',
                '--glass': 'rgba(255,255,255,0.04)',
                '--text': '#e2e8f0',
                '--text-muted': '#94a3b8',
                '--card-border': 'rgba(255,255,255,0.07)',
                '--input-bg': 'rgba(255,255,255,0.05)',
                '--input-border': 'rgba(255,255,255,0.1)',
                '--theme-accent-glow': 'rgba(96,165,250,0.2)',
                '--theme-sidebar-bg': 'rgba(15,23,42,0.8)',
                '--theme-progress-color': '#60a5fa',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'rounded',
            cardBorder: 'subtle',
            fontDisplay: 'Inter',
            progressStyle: 'bar',
            artwork: 'circuit-grid',
            buttonStyle: 'rounded',
            micro: 'glow',
        },
    },
};

// ─────────────────────────────────────────────
// GAMIFIED
// ─────────────────────────────────────────────
const gamified = {
    label: 'Gamified',
    emoji: '🎮',
    description: 'Level up. Earn streaks. Conquer your goals.',
    reward: { key: 'streak', label: 'Streak', unit: 'day streak', emoji: '🔥' },
    terminology: {
        chapter: 'Level',
        topic: 'Quest',
        assessment: 'Boss Battle',
        progress: 'XP',
        streak: 'Flame Streak',
        complete: 'Cleared!',
        locked: 'Locked 🔒',
        level: 'Rank',
    },
    defaultSubTheme: 'aesthetic',
    subThemes: {
        aesthetic: {
            label: 'Aesthetic',
            emoji: '🌸',
            description: 'Soft gradients, dreamy pastels, and gentle animations.',
            palette: {
                '--primary': '#c084fc',
                '--secondary': '#e879f9',
                '--accent': '#f0abfc',
                '--background': '#1a0a2e',
                '--surface': 'rgba(44,16,64,0.9)',
                '--glass': 'rgba(192,132,252,0.08)',
                '--text': '#fae8ff',
                '--text-muted': '#d8b4fe',
                '--card-border': 'rgba(192,132,252,0.2)',
                '--input-bg': 'rgba(255,255,255,0.05)',
                '--input-border': 'rgba(192,132,252,0.25)',
                '--theme-accent-glow': 'rgba(192,132,252,0.35)',
                '--theme-sidebar-bg': 'rgba(44,16,64,0.7)',
                '--theme-progress-color': '#e879f9',
            },
            atmosphere: 'dark',
            cardShape: 'rounded-xl',
            cardBorder: 'glow',
            fontDisplay: 'Outfit',
            progressStyle: 'orbs',
            artwork: 'sakura-petals',
            buttonStyle: 'pill',
            micro: 'sparkle',
        },
        girly: {
            label: 'Girly',
            emoji: '💖',
            description: 'Pink, glitter, and unapologetically fun.',
            palette: {
                '--primary': '#ec4899',
                '--secondary': '#f472b6',
                '--accent': '#fce7f3',
                '--background': '#fff0f6',
                '--surface': 'rgba(255,255,255,0.97)',
                '--glass': 'rgba(252,231,243,0.85)',
                '--text': '#500724',
                '--text-muted': '#9d174d',
                '--card-border': 'rgba(236,72,153,0.15)',
                '--input-bg': '#fff0f6',
                '--input-border': 'rgba(236,72,153,0.2)',
                '--theme-accent-glow': 'rgba(236,72,153,0.2)',
                '--theme-sidebar-bg': '#fce7f3',
                '--theme-progress-color': '#ec4899',
            },
            atmosphere: 'light',
            cardShape: 'pill',
            cardBorder: 'accent',
            fontDisplay: 'Quicksand',
            progressStyle: 'orbs',
            artwork: 'hearts-confetti',
            buttonStyle: 'pill',
            micro: 'sparkle',
        },
        cozy: {
            label: 'Cozy',
            emoji: '🧸',
            description: 'Warm earth tones, soft textures, and snug vibes.',
            palette: {
                '--primary': '#d97706',
                '--secondary': '#f59e0b',
                '--accent': '#fcd34d',
                '--background': '#fefce8',
                '--surface': 'rgba(255,250,235,0.97)',
                '--glass': 'rgba(253,230,138,0.5)',
                '--text': '#451a03',
                '--text-muted': '#92400e',
                '--card-border': 'rgba(217,119,6,0.15)',
                '--input-bg': '#fffbeb',
                '--input-border': 'rgba(217,119,6,0.2)',
                '--theme-accent-glow': 'rgba(217,119,6,0.15)',
                '--theme-sidebar-bg': '#fef3c7',
                '--theme-progress-color': '#d97706',
            },
            atmosphere: 'light',
            cardShape: 'rounded-xl',
            cardBorder: 'subtle',
            fontDisplay: 'Nunito',
            progressStyle: 'bar',
            artwork: 'cozy-window',
            buttonStyle: 'pill',
            micro: 'bounce',
        },
        playful: {
            label: 'Playful',
            emoji: '🪀',
            description: 'Primary colors and bouncy cartoon energy.',
            palette: {
                '--primary': '#2563eb',
                '--secondary': '#ef4444',
                '--accent': '#facc15',
                '--background': '#f0f9ff',
                '--surface': 'rgba(255,255,255,0.98)',
                '--glass': 'rgba(219,234,254,0.7)',
                '--text': '#1e3a5f',
                '--text-muted': '#4b6a8f',
                '--card-border': 'rgba(37,99,235,0.2)',
                '--input-bg': '#ffffff',
                '--input-border': 'rgba(37,99,235,0.25)',
                '--theme-accent-glow': 'rgba(37,99,235,0.2)',
                '--theme-sidebar-bg': '#dbeafe',
                '--theme-progress-color': '#2563eb',
            },
            atmosphere: 'light',
            cardShape: 'rounded-xl',
            cardBorder: 'accent',
            fontDisplay: 'Fredoka One',
            progressStyle: 'orbs',
            artwork: 'toy-blocks',
            buttonStyle: 'pill',
            micro: 'bounce',
        },
        competitive: {
            label: 'Competitive',
            emoji: '🏆',
            description: 'Leaderboards. Rankings. Dominate the class.',
            palette: {
                '--primary': '#7c3aed',
                '--secondary': '#ec4899',
                '--accent': '#a855f7',
                '--background': '#0f172a',
                '--surface': 'rgba(30,41,59,0.9)',
                '--glass': 'rgba(255,255,255,0.05)',
                '--text': '#f8fafc',
                '--text-muted': '#94a3b8',
                '--card-border': 'rgba(255,255,255,0.1)',
                '--input-bg': 'rgba(255,255,255,0.05)',
                '--input-border': 'rgba(255,255,255,0.1)',
                '--theme-accent-glow': 'rgba(124,58,237,0.35)',
                '--theme-sidebar-bg': 'rgba(15,23,42,0.8)',
                '--theme-progress-color': '#a855f7',
            },
            atmosphere: 'dark',
            cardShape: 'rounded',
            cardBorder: 'glow',
            fontDisplay: 'Rajdhani',
            progressStyle: 'xp-ring',
            artwork: 'trophy-sparks',
            buttonStyle: 'rounded',
            micro: 'glow',
        },
        rpg: {
            label: 'RPG',
            emoji: '⚔️',
            description: 'Embark on an epic learning quest. Every topic is a dungeon.',
            palette: {
                '--primary': '#b45309',
                '--secondary': '#d97706',
                '--accent': '#fbbf24',
                '--background': '#1c1007',
                '--surface': 'rgba(44,28,10,0.92)',
                '--glass': 'rgba(180,83,9,0.08)',
                '--text': '#fef3c7',
                '--text-muted': '#d4a855',
                '--card-border': 'rgba(180,83,9,0.3)',
                '--input-bg': 'rgba(255,255,255,0.05)',
                '--input-border': 'rgba(180,83,9,0.3)',
                '--theme-accent-glow': 'rgba(251,191,36,0.3)',
                '--theme-sidebar-bg': 'rgba(28,16,7,0.85)',
                '--theme-progress-color': '#fbbf24',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'sharp',
            cardBorder: 'accent',
            fontDisplay: 'Cinzel',
            progressStyle: 'xp-ring',
            artwork: 'dungeon-map',
            buttonStyle: 'square',
            micro: 'glow',
        },
        pixel: {
            label: 'Pixel',
            emoji: '👾',
            description: '8-bit nostalgia. Retro grids and pixel-perfect precision.',
            palette: {
                '--primary': '#22c55e',
                '--secondary': '#4ade80',
                '--accent': '#86efac',
                '--background': '#000000',
                '--surface': 'rgba(0,30,0,0.95)',
                '--glass': 'rgba(34,197,94,0.06)',
                '--text': '#86efac',
                '--text-muted': '#4ade80',
                '--card-border': 'rgba(34,197,94,0.25)',
                '--input-bg': 'rgba(0,30,0,0.8)',
                '--input-border': 'rgba(34,197,94,0.3)',
                '--theme-accent-glow': 'rgba(34,197,94,0.4)',
                '--theme-sidebar-bg': 'rgba(0,20,0,0.9)',
                '--theme-progress-color': '#22c55e',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'sharp',
            cardBorder: 'glow',
            fontDisplay: 'Press Start 2P',
            progressStyle: 'orbs',
            artwork: 'pixel-grid',
            buttonStyle: 'square',
            micro: 'flicker',
        },
        cyber: {
            label: 'Cyber',
            emoji: '🤖',
            description: 'Neon-drenched cyberpunk. Neural links and data streams.',
            palette: {
                '--primary': '#06b6d4',
                '--secondary': '#22d3ee',
                '--accent': '#67e8f9',
                '--background': '#020617',
                '--surface': 'rgba(2,16,40,0.95)',
                '--glass': 'rgba(6,182,212,0.06)',
                '--text': '#e0f2fe',
                '--text-muted': '#7dd3fc',
                '--card-border': 'rgba(6,182,212,0.2)',
                '--input-bg': 'rgba(6,182,212,0.05)',
                '--input-border': 'rgba(6,182,212,0.25)',
                '--theme-accent-glow': 'rgba(6,182,212,0.4)',
                '--theme-sidebar-bg': 'rgba(2,10,30,0.9)',
                '--theme-progress-color': '#06b6d4',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'sharp',
            cardBorder: 'glow',
            fontDisplay: 'Share Tech Mono',
            progressStyle: 'bar',
            artwork: 'cyber-grid',
            buttonStyle: 'square',
            micro: 'flicker',
        },
    },
};

// ─────────────────────────────────────────────
// CINEMATIC
// ─────────────────────────────────────────────
const cinematic = {
    label: 'Cinematic',
    emoji: '🎬',
    description: 'Your learning story. Every topic is a scene.',
    reward: { key: 'tokens', label: 'Tokens', unit: 'tokens', emoji: '🎟️' },
    terminology: {
        chapter: 'Act',
        topic: 'Scene',
        assessment: 'Audition',
        progress: 'Story Arc',
        streak: 'Shooting Days',
        complete: 'Scene Cut ✂️',
        locked: 'Coming Soon…',
        level: 'Episode',
    },
    defaultSubTheme: 'classic',
    subThemes: {
        action: {
            label: 'Action',
            emoji: '💥',
            description: 'Fast-paced, explosive. Never a dull moment.',
            palette: {
                '--primary': '#ef4444',
                '--secondary': '#f97316',
                '--accent': '#fbbf24',
                '--background': '#0c0a09',
                '--surface': 'rgba(28,20,12,0.95)',
                '--glass': 'rgba(239,68,68,0.07)',
                '--text': '#fef9ee',
                '--text-muted': '#d4a04a',
                '--card-border': 'rgba(239,68,68,0.25)',
                '--input-bg': 'rgba(239,68,68,0.05)',
                '--input-border': 'rgba(239,68,68,0.25)',
                '--theme-accent-glow': 'rgba(239,68,68,0.4)',
                '--theme-sidebar-bg': 'rgba(18,10,5,0.9)',
                '--theme-progress-color': '#ef4444',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'sharp',
            cardBorder: 'accent',
            fontDisplay: 'Oswald',
            progressStyle: 'film-strip',
            artwork: 'explosion-sparks',
            buttonStyle: 'square',
            micro: 'flicker',
        },
        thriller: {
            label: 'Thriller',
            emoji: '🔪',
            description: 'Shadowy, high-stakes tension. Every answer matters.',
            palette: {
                '--primary': '#64748b',
                '--secondary': '#94a3b8',
                '--accent': '#e2e8f0',
                '--background': '#060608',
                '--surface': 'rgba(10,10,15,0.97)',
                '--glass': 'rgba(255,255,255,0.04)',
                '--text': '#f1f5f9',
                '--text-muted': '#64748b',
                '--card-border': 'rgba(255,255,255,0.06)',
                '--input-bg': 'rgba(255,255,255,0.04)',
                '--input-border': 'rgba(255,255,255,0.08)',
                '--theme-accent-glow': 'rgba(148,163,184,0.15)',
                '--theme-sidebar-bg': 'rgba(5,5,8,0.95)',
                '--theme-progress-color': '#94a3b8',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'sharp',
            cardBorder: 'subtle',
            fontDisplay: 'Playfair Display',
            progressStyle: 'film-strip',
            artwork: 'rain-noir',
            buttonStyle: 'square',
            micro: 'slide',
        },
        romance: {
            label: 'Romance / Soft',
            emoji: '🌹',
            description: 'Golden hour warmth, florals and slow-burn cinematic glow.',
            palette: {
                '--primary': '#f43f5e',
                '--secondary': '#fb7185',
                '--accent': '#fda4af',
                '--background': '#1a0a0a',
                '--surface': 'rgba(44,16,20,0.95)',
                '--glass': 'rgba(244,63,94,0.07)',
                '--text': '#fff1f2',
                '--text-muted': '#fda4af',
                '--card-border': 'rgba(244,63,94,0.2)',
                '--input-bg': 'rgba(244,63,94,0.05)',
                '--input-border': 'rgba(244,63,94,0.2)',
                '--theme-accent-glow': 'rgba(244,63,94,0.3)',
                '--theme-sidebar-bg': 'rgba(30,10,14,0.9)',
                '--theme-progress-color': '#f43f5e',
            },
            atmosphere: 'dark',
            cardShape: 'rounded-xl',
            cardBorder: 'glow',
            fontDisplay: 'Cormorant Garamond',
            progressStyle: 'stardust',
            artwork: 'rose-petals',
            buttonStyle: 'pill',
            micro: 'sparkle',
        },
        'sci-fi': {
            label: 'Sci-Fi',
            emoji: '🚀',
            description: 'Cold steel, holographic overlays, and galactic ambition.',
            palette: {
                '--primary': '#818cf8',
                '--secondary': '#a5b4fc',
                '--accent': '#c7d2fe',
                '--background': '#03001c',
                '--surface': 'rgba(5,5,40,0.95)',
                '--glass': 'rgba(129,140,248,0.07)',
                '--text': '#e0e7ff',
                '--text-muted': '#a5b4fc',
                '--card-border': 'rgba(129,140,248,0.2)',
                '--input-bg': 'rgba(129,140,248,0.05)',
                '--input-border': 'rgba(129,140,248,0.2)',
                '--theme-accent-glow': 'rgba(129,140,248,0.35)',
                '--theme-sidebar-bg': 'rgba(3,0,25,0.9)',
                '--theme-progress-color': '#818cf8',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'sharp',
            cardBorder: 'glow',
            fontDisplay: 'Exo 2',
            progressStyle: 'film-strip',
            artwork: 'hologram-grid',
            buttonStyle: 'square',
            micro: 'glow',
        },
        fantasy: {
            label: 'Fantasy',
            emoji: '🧙',
            description: 'Enchanted forests, arcane runes, and mystical glow.',
            palette: {
                '--primary': '#4ade80',
                '--secondary': '#86efac',
                '--accent': '#bbf7d0',
                '--background': '#050d07',
                '--surface': 'rgba(10,22,12,0.95)',
                '--glass': 'rgba(74,222,128,0.07)',
                '--text': '#ecfdf5',
                '--text-muted': '#86efac',
                '--card-border': 'rgba(74,222,128,0.2)',
                '--input-bg': 'rgba(74,222,128,0.05)',
                '--input-border': 'rgba(74,222,128,0.2)',
                '--theme-accent-glow': 'rgba(74,222,128,0.3)',
                '--theme-sidebar-bg': 'rgba(5,12,7,0.9)',
                '--theme-progress-color': '#4ade80',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'rounded-xl',
            cardBorder: 'glow',
            fontDisplay: 'Cinzel Decorative',
            progressStyle: 'stardust',
            artwork: 'forest-runes',
            buttonStyle: 'rounded',
            micro: 'sparkle',
        },
        space: {
            label: 'Space Adventure',
            emoji: '🌌',
            description: 'Nebulae, star fields, and zero-gravity curiosity.',
            palette: {
                '--primary': '#a78bfa',
                '--secondary': '#c4b5fd',
                '--accent': '#ddd6fe',
                '--background': '#000005',
                '--surface': 'rgba(5,3,18,0.97)',
                '--glass': 'rgba(167,139,250,0.06)',
                '--text': '#ede9fe',
                '--text-muted': '#a78bfa',
                '--card-border': 'rgba(167,139,250,0.15)',
                '--input-bg': 'rgba(167,139,250,0.05)',
                '--input-border': 'rgba(167,139,250,0.18)',
                '--theme-accent-glow': 'rgba(167,139,250,0.3)',
                '--theme-sidebar-bg': 'rgba(2,2,15,0.95)',
                '--theme-progress-color': '#a78bfa',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'rounded',
            cardBorder: 'glow',
            fontDisplay: 'Orbitron',
            progressStyle: 'stardust',
            artwork: 'star-field',
            buttonStyle: 'pill',
            micro: 'glow',
        },
        classic: {
            label: 'Classic Cinema',
            emoji: '🎞️',
            description: 'Old Hollywood glamour. Film grain and warm amber light.',
            palette: {
                '--primary': '#f59e0b',
                '--secondary': '#b45309',
                '--accent': '#fbbf24',
                '--background': '#111111',
                '--surface': 'rgba(20,18,12,0.95)',
                '--glass': 'rgba(245,158,11,0.06)',
                '--text': '#f5f5f0',
                '--text-muted': '#a3a3a3',
                '--card-border': 'rgba(245,158,11,0.2)',
                '--input-bg': 'rgba(255,255,255,0.05)',
                '--input-border': 'rgba(245,158,11,0.2)',
                '--theme-accent-glow': 'rgba(245,158,11,0.25)',
                '--theme-sidebar-bg': 'rgba(12,10,5,0.92)',
                '--theme-progress-color': '#f59e0b',
            },
            atmosphere: 'ultra-dark',
            cardShape: 'rounded',
            cardBorder: 'accent',
            fontDisplay: 'Playfair Display',
            progressStyle: 'film-strip',
            artwork: 'film-reel',
            buttonStyle: 'rounded',
            micro: 'slide',
        },
        anime: {
            label: 'Anime-Inspired',
            emoji: '✨',
            description: 'Vibrant energy, speed lines, and kawaii power-ups.',
            palette: {
                '--primary': '#f472b6',
                '--secondary': '#818cf8',
                '--accent': '#38bdf8',
                '--background': '#0d0d1a',
                '--surface': 'rgba(20,20,40,0.95)',
                '--glass': 'rgba(244,114,182,0.07)',
                '--text': '#fef9ff',
                '--text-muted': '#c4b5fd',
                '--card-border': 'rgba(244,114,182,0.2)',
                '--input-bg': 'rgba(244,114,182,0.05)',
                '--input-border': 'rgba(244,114,182,0.2)',
                '--theme-accent-glow': 'rgba(244,114,182,0.35)',
                '--theme-sidebar-bg': 'rgba(10,10,22,0.9)',
                '--theme-progress-color': '#f472b6',
            },
            atmosphere: 'dark',
            cardShape: 'rounded-xl',
            cardBorder: 'glow',
            fontDisplay: 'M PLUS Rounded 1c',
            progressStyle: 'orbs',
            artwork: 'speed-lines',
            buttonStyle: 'pill',
            micro: 'sparkle',
        },
    },
};

// ─────────────────────────────────────────────
// MASTER CONFIG EXPORT
// ─────────────────────────────────────────────
export const EXPERIENCE_CONFIG = { professional, gamified, cinematic };

/**
 * Get the full config for a specific experience + sub-theme combination.
 * Always returns a valid config — falls back to professional/corporate if invalid.
 *
 * @param {'professional'|'gamified'|'cinematic'} experience
 * @param {string} subTheme
 * @returns {{ experience, subTheme, experienceCfg, subThemeCfg, terminology, reward }}
 */
export function getThemeConfig(experience, subTheme) {
    const expCfg = EXPERIENCE_CONFIG[experience] || EXPERIENCE_CONFIG.professional;
    const resolvedSubTheme = subTheme && expCfg.subThemes[subTheme]
        ? subTheme
        : expCfg.defaultSubTheme;
    const subThemeCfg = expCfg.subThemes[resolvedSubTheme];

    return {
        experience,
        subTheme: resolvedSubTheme,
        experienceCfg: expCfg,
        subThemeCfg,
        terminology: expCfg.terminology,
        reward: expCfg.reward,
        palette: subThemeCfg.palette,
        atmosphere: subThemeCfg.atmosphere,
        cardShape: subThemeCfg.cardShape,
        cardBorder: subThemeCfg.cardBorder,
        fontDisplay: subThemeCfg.fontDisplay,
        progressStyle: subThemeCfg.progressStyle,
        artwork: subThemeCfg.artwork,
        buttonStyle: subThemeCfg.buttonStyle,
        micro: subThemeCfg.micro,
    };
}
